package com.acme.salary.common.audit;

import com.acme.salary.common.persistence.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * One recorded business action: who, what, when (FR-8.1).
 *
 * <p>Append-only. There is no setter, no update path and no delete: an audit trail that
 * can be edited is not an audit trail. Rows are written inside the same transaction as
 * the change they describe, so neither can exist without the other (ADR-013).
 *
 * <p>The action names a business event — {@code SALARY_STRUCTURE_ASSIGNED} — rather than a
 * table mutation, which is the reason this is hand-written rather than generated by
 * Envers.
 */
@Entity
@Table(name = "audit_events")
public class AuditEvent extends BaseEntity {

    /** Null only for system-initiated actions; every user-driven change has an actor. */
    @Column(name = "actor_user_id")
    private Long actorUserId;

    @Column(name = "entity_type", nullable = false, length = 60)
    private String entityType;

    @Column(name = "entity_id")
    private Long entityId;

    @Column(name = "action", nullable = false, length = 60)
    private String action;

    /**
     * Free-form JSON context — the figures involved, the reason given for an override.
     * Never the whole record: an audit row must not become a second copy of salary data
     * with different access rules (NFR-2.7).
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "details")
    private String details;

    @Column(name = "occurred_at", nullable = false, updatable = false)
    private Instant occurredAt;

    protected AuditEvent() {
        // for JPA
    }

    public AuditEvent(
            Long actorUserId,
            String entityType,
            Long entityId,
            String action,
            String details,
            Instant occurredAt) {
        this.actorUserId = actorUserId;
        this.entityType = entityType;
        this.entityId = entityId;
        this.action = action;
        this.details = details;
        this.occurredAt = occurredAt;
    }

    public Long getActorUserId() {
        return actorUserId;
    }

    public String getEntityType() {
        return entityType;
    }

    public Long getEntityId() {
        return entityId;
    }

    public String getAction() {
        return action;
    }

    public String getDetails() {
        return details;
    }

    public Instant getOccurredAt() {
        return occurredAt;
    }
}
