-- Baseline schema for ACME Salary Management.
--
-- Invariants that must hold under concurrency live here as constraints rather than only
-- in Java (architecture §7.2): a race between two requests cannot break a UNIQUE index,
-- but it can defeat a service-layer pre-check. Money is NUMERIC(12,2) everywhere
-- (ADR-006). Reference data uses ON DELETE RESTRICT so rows in use cannot be removed
-- (FR-3.3). Nothing is ever hard-deleted (ADR-014).

------------------------------------------------------------------------------------------
-- Users and authentication
------------------------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Bumped on password change and deactivation to invalidate outstanding tokens; the
    -- partial answer to JWTs being unrevokable (ADR-004).
    token_version INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Email is the login identifier, so case must not create a second account.
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'HR', 'EMPLOYEE'))
);
CREATE UNIQUE INDEX uq_users_email_key ON users (email);

------------------------------------------------------------------------------------------
-- Organisation reference data
------------------------------------------------------------------------------------------
CREATE TABLE departments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(20)  NOT NULL,
    name             VARCHAR(120) NOT NULL,
    head_employee_id BIGINT,                       -- FK added after employees exists
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_departments_code ON departments (code);

CREATE TABLE designations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_designations_title ON designations (title);

CREATE TABLE grades (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(60)   NOT NULL,
    min_ctc    NUMERIC(12,2),
    max_ctc    NUMERIC(12,2),
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_grades_ctc_non_negative CHECK (
        (min_ctc IS NULL OR min_ctc >= 0) AND (max_ctc IS NULL OR max_ctc >= 0)),
    CONSTRAINT ck_grades_ctc_band CHECK (
        min_ctc IS NULL OR max_ctc IS NULL OR max_ctc >= min_ctc)
);
CREATE UNIQUE INDEX uq_grades_name ON grades (name);

------------------------------------------------------------------------------------------
-- Employees
------------------------------------------------------------------------------------------
CREATE TABLE employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code   VARCHAR(20)  NOT NULL,
    first_name      VARCHAR(80)  NOT NULL,
    last_name       VARCHAR(80)  NOT NULL,
    work_email      VARCHAR(255) NOT NULL,
    date_of_joining DATE         NOT NULL,
    exit_date       DATE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    department_id   BIGINT       NOT NULL,
    designation_id  BIGINT       NOT NULL,
    grade_id        BIGINT       NOT NULL,
    user_id         BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_employees_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_employees_exit_after_joining CHECK (
        exit_date IS NULL OR exit_date >= date_of_joining),
    -- An INACTIVE employee must carry an exit date: payroll eligibility is derived from
    -- it (FR-2.6), so a leaver without one would silently stay eligible.
    CONSTRAINT ck_employees_inactive_has_exit_date CHECK (
        status <> 'INACTIVE' OR exit_date IS NOT NULL),
    CONSTRAINT fk_employees_department FOREIGN KEY (department_id)
        REFERENCES departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_employees_designation FOREIGN KEY (designation_id)
        REFERENCES designations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_employees_grade FOREIGN KEY (grade_id)
        REFERENCES grades (id) ON DELETE RESTRICT,
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uq_employees_code ON employees (employee_code);
CREATE UNIQUE INDEX uq_employees_work_email ON employees (work_email);
CREATE UNIQUE INDEX uq_employees_user ON employees (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX ix_employees_department ON employees (department_id);
CREATE INDEX ix_employees_status ON employees (status);

ALTER TABLE departments
    ADD CONSTRAINT fk_departments_head_employee FOREIGN KEY (head_employee_id)
        REFERENCES employees (id) ON DELETE SET NULL;

------------------------------------------------------------------------------------------
-- Salary component definitions
------------------------------------------------------------------------------------------
CREATE TABLE salary_components (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(30)   NOT NULL,
    name             VARCHAR(120)  NOT NULL,
    type             VARCHAR(20)   NOT NULL,
    calculation_type VARCHAR(30)   NOT NULL,
    default_value    NUMERIC(12,2) NOT NULL DEFAULT 0,
    taxable          BOOLEAN       NOT NULL DEFAULT TRUE,
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_salary_components_type CHECK (type IN ('EARNING', 'DEDUCTION')),
    -- A closed set by decision: no user-authored formulas are ever evaluated (ADR-016).
    CONSTRAINT ck_salary_components_calc CHECK (calculation_type IN ('FLAT', 'PERCENT_OF_BASIC')),
    CONSTRAINT ck_salary_components_value CHECK (default_value >= 0),
    CONSTRAINT ck_salary_components_percent_range CHECK (
        calculation_type <> 'PERCENT_OF_BASIC' OR default_value <= 100)
);
CREATE UNIQUE INDEX uq_salary_components_code ON salary_components (code);

------------------------------------------------------------------------------------------
-- Salary structures: effective-dated and append-only (ADR-009)
------------------------------------------------------------------------------------------
CREATE TABLE salary_structures (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT      NOT NULL,
    effective_from DATE        NOT NULL,
    superseded_on  DATE,
    override_reason VARCHAR(500),               -- required when outside the grade band (FR-4.3)
    created_by     BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_salary_structures_superseded_after_effective CHECK (
        superseded_on IS NULL OR superseded_on > effective_from),
    CONSTRAINT fk_salary_structures_employee FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_salary_structures_created_by FOREIGN KEY (created_by)
        REFERENCES users (id) ON DELETE RESTRICT
);
-- One structure per employee per effective date, and at most one open (current) revision.
CREATE UNIQUE INDEX uq_salary_structures_employee_effective
    ON salary_structures (employee_id, effective_from);
CREATE UNIQUE INDEX uq_salary_structures_one_current
    ON salary_structures (employee_id) WHERE superseded_on IS NULL;
CREATE INDEX ix_salary_structures_employee_effective_desc
    ON salary_structures (employee_id, effective_from DESC);

CREATE TABLE salary_structure_components (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id BIGINT        NOT NULL,
    component_id BIGINT        NOT NULL,
    value        NUMERIC(12,2) NOT NULL,
    CONSTRAINT ck_structure_components_value CHECK (value >= 0),
    CONSTRAINT fk_structure_components_structure FOREIGN KEY (structure_id)
        REFERENCES salary_structures (id) ON DELETE CASCADE,
    CONSTRAINT fk_structure_components_component FOREIGN KEY (component_id)
        REFERENCES salary_components (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uq_structure_components
    ON salary_structure_components (structure_id, component_id);

------------------------------------------------------------------------------------------
-- Payroll runs
------------------------------------------------------------------------------------------
CREATE TABLE payroll_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_year       INTEGER       NOT NULL,
    period_month      INTEGER       NOT NULL,
    status            VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    employee_count    INTEGER       NOT NULL DEFAULT 0,
    total_gross       NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_deductions  NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_net         NUMERIC(14,2) NOT NULL DEFAULT 0,
    initiated_by      BIGINT        NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    finalised_at      TIMESTAMPTZ,
    cancelled_at      TIMESTAMPTZ,
    CONSTRAINT ck_payroll_runs_month CHECK (period_month BETWEEN 1 AND 12),
    CONSTRAINT ck_payroll_runs_year CHECK (period_year BETWEEN 2000 AND 2100),
    CONSTRAINT ck_payroll_runs_status CHECK (status IN ('DRAFT', 'FINALISED', 'CANCELLED')),
    CONSTRAINT ck_payroll_runs_totals CHECK (
        total_gross >= 0 AND total_deductions >= 0
        AND total_net = total_gross - total_deductions),
    -- Terminal states carry their timestamp, and only theirs (ADR-010).
    CONSTRAINT ck_payroll_runs_finalised_at CHECK (
        (status = 'FINALISED') = (finalised_at IS NOT NULL)),
    CONSTRAINT ck_payroll_runs_cancelled_at CHECK (
        (status = 'CANCELLED') = (cancelled_at IS NOT NULL)),
    CONSTRAINT fk_payroll_runs_initiated_by FOREIGN KEY (initiated_by)
        REFERENCES users (id) ON DELETE RESTRICT
);
-- FR-5.7 precisely: a period may hold at most one DRAFT or FINALISED run, while a
-- CANCELLED run must not block a retry. A plain UNIQUE constraint would block it.
CREATE UNIQUE INDEX uq_payroll_runs_active_period
    ON payroll_runs (period_year, period_month)
    WHERE status IN ('DRAFT', 'FINALISED');
CREATE INDEX ix_payroll_runs_period ON payroll_runs (period_year DESC, period_month DESC);

------------------------------------------------------------------------------------------
-- Payslips: computed with the draft run, published on finalisation (FR-5.8, ADR-010)
------------------------------------------------------------------------------------------
CREATE TABLE payslips (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_run_id   BIGINT        NOT NULL,
    employee_id      BIGINT        NOT NULL,
    total_days       INTEGER       NOT NULL,
    paid_days        INTEGER       NOT NULL,
    lop_days         INTEGER       NOT NULL DEFAULT 0,
    gross_pay        NUMERIC(12,2) NOT NULL,
    total_deductions NUMERIC(12,2) NOT NULL,
    net_pay          NUMERIC(12,2) NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_payslips_days CHECK (
        total_days BETWEEN 28 AND 31
        AND lop_days >= 0
        AND paid_days >= 0
        AND paid_days + lop_days = total_days),
    CONSTRAINT ck_payslips_amounts CHECK (
        gross_pay >= 0 AND total_deductions >= 0
        AND net_pay = gross_pay - total_deductions),
    CONSTRAINT fk_payslips_run FOREIGN KEY (payroll_run_id)
        REFERENCES payroll_runs (id) ON DELETE CASCADE,
    CONSTRAINT fk_payslips_employee FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uq_payslips_run_employee ON payslips (payroll_run_id, employee_id);
CREATE INDEX ix_payslips_employee ON payslips (employee_id, created_at DESC);

CREATE TABLE payslip_lines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id     BIGINT        NOT NULL,
    component_code VARCHAR(30)   NOT NULL,
    -- Name and type are copied, not joined: a payslip must render exactly as published
    -- even if the component definition is later renamed (ADR-010).
    component_name VARCHAR(120)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    amount         NUMERIC(12,2) NOT NULL,
    sort_order     INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT ck_payslip_lines_type CHECK (type IN ('EARNING', 'DEDUCTION')),
    CONSTRAINT ck_payslip_lines_amount CHECK (amount >= 0),
    CONSTRAINT fk_payslip_lines_payslip FOREIGN KEY (payslip_id)
        REFERENCES payslips (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_payslip_lines_payslip_component
    ON payslip_lines (payslip_id, component_code);
CREATE INDEX ix_payslip_lines_payslip ON payslip_lines (payslip_id, sort_order);

------------------------------------------------------------------------------------------
-- Audit trail: append-only (FR-8.1, ADR-013)
------------------------------------------------------------------------------------------
CREATE TABLE audit_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,                        -- null only for system-initiated actions
    entity_type   VARCHAR(60)  NOT NULL,
    entity_id     BIGINT,
    action        VARCHAR(60)  NOT NULL,
    details       JSONB,
    occurred_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_audit_events_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_audit_events_entity ON audit_events (entity_type, entity_id, occurred_at DESC);
CREATE INDEX ix_audit_events_actor ON audit_events (actor_user_id, occurred_at DESC);
CREATE INDEX ix_audit_events_occurred_at ON audit_events (occurred_at DESC);
