package com.acme.salary.common.persistence;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.util.Objects;

/**
 * Identity for every persistent entity.
 *
 * <p>Ids are database-generated identity columns, matching the
 * {@code GENERATED BY DEFAULT AS IDENTITY} columns in the baseline migration.
 *
 * <p>Equality is by id and concrete type. Two unsaved entities are equal only if they are
 * the same object: giving them all the "null id" equality would make a {@code Set} of new
 * entities collapse to one element.
 */
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    public Long getId() {
        return id;
    }

    /** True before the entity has been persisted. */
    public boolean isNew() {
        return id == null;
    }

    @Override
    public final boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BaseEntity that) || !getClass().equals(other.getClass())) {
            return false;
        }
        return id != null && id.equals(that.id);
    }

    @Override
    public final int hashCode() {
        // Constant for unsaved entities, so a hash-based collection keeps working if an
        // entity is added before it is persisted and acquires its id.
        return id == null ? Objects.hash(getClass()) : id.hashCode();
    }
}
